apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cbz-backend
  labels:
    app: cbz-backend
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: cbz-backend
  template:
    metadata: 
      labels:
        app: cbz-backend
    spec:
      containers:
        - name: cbz-backend
          image: shubhamkalsait1/cbz-three-tier-backend:latest
          ports:
          - containerPort: 8080
            name: java