apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cbz-backend-1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cbz-backend-1
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50